from enum import Enum


class RuntimeState(str, Enum):
    SYNCING = "SYNCING"
    SYNC_REQUIRED = "SYNC_REQUIRED"
    IDLE = "IDLE"
    CAST_PENDING = "CAST_PENDING"
    WAITING = "WAITING"
    READY = "READY"
    HOOK_PENDING = "HOOK_PENDING"
    HOOK = "HOOK"
    RESULT_PENDING = "RESULT_PENDING"
    PRESS = "PRESS"
    GET = "GET"
    COLLECT_PENDING = "COLLECT_PENDING"
